version: '3.7'

services:
  master:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    volumes:
      - es:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
  curator:
    image: itzg/elasticsearch-curator

volumes:
  es: {}